services:
  sbplayer:
    image: origeva/sbplayer
    build: .
    restart: unless-stopped
    environment:
      - APPLICATION_ID=
      - BOT_SECRET=
      - YOUTUBE_API_TOKEN=
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
      - SPOTIFY_REDIRECT_URI=
    ports:
      - '80:80'
